FishyBuisness_3/Models/ErrorViewModel.cs
namespace FishyBuisness_3.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

FishyBuisness_3/Models/Fish.cs
namespace FishyBuisness_3.Models
{
	public class Fish
	{
		public int FishId { get; set; }
		public string FishName { get; set; }
		public string FishDescription { get; set; }
		public string Spieces { get; set; }
		public string Habitat { get; set; }
		public double Lenght { get; set; }
		public double Weight { get; set; }
		public double Price { get; set; }

	}
}

FishyBuisness_3/Controllers/FishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FishyBuisness_3.Data;
using FishyBuisness_3.Models;

namespace FishyBuisness_3.Controllers
{
    public class FishController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FishController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Fish
        public async Task<IActionResult> Index()
        {
            return View(await _context.Fish.ToListAsync());
        }

        // GET: Fish/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fish = await _context.Fish
                .FirstOrDefaultAsync(m => m.FishId == id);
            if (fish == null)
            {
                return NotFound();
            }

            return View(fish);
        }

        // GET: Fish/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fish/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FishId,FishName,FishDescription,Spieces,Habitat,Lenght,Weight,Price")] Fish fish)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fish);
        }

        // GET: Fish/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fish = await _context.Fish.FindAsync(id);
            if (fish == null)
            {
                return NotFound();
            }
            return View(fish);
        }

        // POST: Fish/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FishId,FishName,FishDescription,Spieces,Habitat,Lenght,Weight,Price")] Fish fish)
        {
            if (id != fish.FishId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FishExists(fish.FishId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fish);
        }

        // GET: Fish/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fish = await _context.Fish
                .FirstOrDefaultAsync(m => m.FishId == id);
            if (fish == null)
            {
                return NotFound();
            }

            return View(fish);
        }

        // POST: Fish/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fish = await _context.Fish.FindAsync(id);
            if (fish != null)
            {
                _context.Fish.Remove(fish);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FishExists(int id)
        {
            return _context.Fish.Any(e => e.FishId == id);
        }
    }
}

FishyBuisness_3/Controllers/HomeController.cs
using FishyBuisness_3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FishyBuisness_3.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

FishyBuisness_3/Views/Fish/Create.cshtml
@model FishyBuisness_3.Models.Fish

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Fish</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FishName" class="control-label"></label>
                <input asp-for="FishName" class="form-control" />
                <span asp-validation-for="FishName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FishDescription" class="control-label"></label>
                <input asp-for="FishDescription" class="form-control" />
                <span asp-validation-for="FishDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spieces" class="control-label"></label>
                <input asp-for="Spieces" class="form-control" />
                <span asp-validation-for="Spieces" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitat" class="control-label"></label>
                <input asp-for="Habitat" class="form-control" />
                <span asp-validation-for="Habitat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lenght" class="control-label"></label>
                <input asp-for="Lenght" class="form-control" />
                <span asp-validation-for="Lenght" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FishyBuisness_3/Views/Fish/Delete.cshtml
@model FishyBuisness_3.Models.Fish

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Fish</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FishName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FishName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FishDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FishDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spieces)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spieces)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Habitat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Habitat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lenght)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lenght)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FishId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FishyBuisness_3/Views/Fish/Details.cshtml
@model FishyBuisness_3.Models.Fish

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Fish</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FishName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FishName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FishDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FishDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spieces)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spieces)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Habitat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Habitat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lenght)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lenght)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FishId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FishyBuisness_3/Views/Fish/Edit.cshtml
@model FishyBuisness_3.Models.Fish

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Fish</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FishId" />
            <div class="form-group">
                <label asp-for="FishName" class="control-label"></label>
                <input asp-for="FishName" class="form-control" />
                <span asp-validation-for="FishName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FishDescription" class="control-label"></label>
                <input asp-for="FishDescription" class="form-control" />
                <span asp-validation-for="FishDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spieces" class="control-label"></label>
                <input asp-for="Spieces" class="form-control" />
                <span asp-validation-for="Spieces" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitat" class="control-label"></label>
                <input asp-for="Habitat" class="form-control" />
                <span asp-validation-for="Habitat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lenght" class="control-label"></label>
                <input asp-for="Lenght" class="form-control" />
                <span asp-validation-for="Lenght" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FishyBuisness_3/Views/Fish/Index.cshtml
@model IEnumerable<FishyBuisness_3.Models.Fish>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FishName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FishDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spieces)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Habitat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lenght)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FishName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FishDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spieces)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Habitat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lenght)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FishId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FishId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FishId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FishyBuisness_3/Views/Fish/View.cshtml
@model IEnumerable<FishyBuisness_3.Models.Fish>

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FishName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FishDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spieces)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Habitat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lenght)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FishName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FishDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spieces)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Habitat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lenght)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FishId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FishId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FishId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FishyBuisness_3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FishyBuisness_3/Views/Home/View.cshtml
@model IEnumerable<FishyBuisness_3.Models.Fish>

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FishName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FishDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spieces)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Habitat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lenght)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FishName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FishDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spieces)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Habitat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lenght)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FishId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FishId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FishId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FishyBuisness_3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FishyBuisness_3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FishyBuisness_3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FishyBuisness_3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fish" asp-action="Index">Fish</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FishyBuisness_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>